invoices/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('user_invoice.urls')),
    path('leave/', include('leave.urls')), 
    path('letter/', include('letter.urls')),
    path('manage_user/', include('manage_user.urls')),
    path('account_management/', include('account_management.urls')),
    path('expenses/', include('expenses.urls')),
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(template_name='user_invoice/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user_invoice/logout.html'),name='logout'),

    
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leave/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.LeaveRequestAddView.as_view(), name='leave'),
    path('ajax/leave_bal', views.leave_bal, name="leave_bal"),
    path('approve-leave/', views.LeaveRequestDisplayView.as_view(), name="approve_leave"),
    path('toapprove/<int:pk>', views.ToApprove.as_view(), name="to_approve"),
    path('topending/<int:pk>', views.ToPending.as_view(), name="to_pending"),
    #path('topending/', views.ToPending.as_view(), name="to_pending"),

    path('ajax/check_overlap_leave', views.check_overlap_leave, name="check_overlap_leave")

    ]

letter/urls.py
from django.urls import path
from . import views

app_name = "letter"

urlpatterns = [
    path("",views.employeeList,name="joinee_list"),
    path("add/",views.createEmployee,name="add_joinee"),
    path("edit/<int:pk>",views.editEmployee,name="edit_joinee"),
    path("pdfGenerate/<str:pk>/",views.generatePDF,name="pdf-generate"),

    path("ajax/get_user_data", views.ajax_get_user_data,name="get_user_data"),
]

letter/models.py
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.
class EmployeeDetail(models.Model):
    first_name              = models.CharField(max_length=200)
    last_name               = models.CharField(max_length=200)
    designation             = models.CharField(max_length=100)
    ctc                     = models.PositiveIntegerField()
    joining_date            = models.DateField(blank=False)
    email                   = models.EmailField(null=True,blank=True)
    phone_regex             = RegexValidator(regex=r'^\+?1?\d{9,12}$', message="Phone number must consist of 10 digits.(Like 1234567890)")
    phone                   = models.CharField(validators=[phone_regex],max_length=10,blank=True,null=True)
    created_at              = models.DateField(auto_now_add=True)


    def __str__(self):
        return '%s' % self.first_name+' '+self.last_name
        # return self.first_name+" "+self.last_name

    class Meta:
        verbose_name_plural = "Employee Details"
        ordering = ['-id']

letter/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,reverse, get_object_or_404
from django.core.paginator import Paginator
from django.views.generic import View
from django.contrib import messages
import datetime
import math

from user_invoice.models import Employee
from django.contrib.auth.models import User

from manage_user.models import Userdetail

from .converter import convertToWords
from .models import EmployeeDetail
from .utils import *

from django.http import JsonResponse

# Create your views here.

def ajax_get_user_data(request):
	user_id = request.GET.get('user_id', None)
	user    = Userdetail.objects.get(pk=user_id)
	data = {'id':user.pk, 'username':user.username, 'firstname':user.firstname, 'lastname':user.lastname, 'phone':user.phone, 'email':user.email, 'address':user.address}
	return JsonResponse(data)

def createEmployee(request):
	user           = request.user
	employee       = Employee.objects.get(auth_tbl=user)
	rolename       = employee.role.name.lower()
	users          = Userdetail.objects.all().order_by('firstname')

	if request.method=="POST":
		form = EmployeeDetail.objects.create(
			first_name 		= request.POST['first_name'],
			last_name 		= request.POST['last_name'],
			designation 	= request.POST['designation'],
			email 			= request.POST['email'],
			phone 			= request.POST['phone'],
			joining_date 	= request.POST['joining_date'],
			ctc 			= request.POST['ctc'],
		)
		form.save()
		messages.success(request,'Employee Just Added')
		return HttpResponseRedirect(reverse('letter:joinee_list'))
	
	return render(request,'letter/add_employee.html', {'role':rolename, "employee":employee, 'users':users})

def editEmployee(request, pk):
	user           = request.user
	employee       = Employee.objects.get(auth_tbl=user)
	rolename       = employee.role.name.lower()
	users          = Userdetail.objects.all().order_by('firstname')
	joinee         = EmployeeDetail.objects.get(pk=pk)
	print(joinee)
	joinee         = get_object_or_404(EmployeeDetail, pk=pk)

	print(request.POST)
	if request.method=="POST":
		print(request.POST['first_name'])
		print(request.POST['last_name'])
		print(request.POST['designation'])
		print(request.POST['email'])
		print(request.POST['phone'])
		print(request.POST['joining_date'])
		print(request.POST['ctc'])
		
		joinee.first_name 		= request.POST['first_name']
		joinee.last_name 		= request.POST['last_name']
		joinee.designation 	    = request.POST['designation']
		joinee.email 			= request.POST['email']
		joinee.phone 			= request.POST['phone']
		joinee.joining_date 	= request.POST['joining_date']
		joinee.ctc 		     	= request.POST['ctc']
		print(joinee)
		joinee.save()
		messages.success(request,'Employee Just Edited')
		return HttpResponseRedirect(reverse('letter:joinee_list'))
	
	return render(request,'letter/add_employee.html', {'role':rolename, "employee":employee, 'users':users,'joinee':joinee})


def employeeList(request):
	employee_list = EmployeeDetail.objects.all()

	firstName = request.POST.get('first_name')
	lastName = request.POST.get('last_name')

	if firstName != '' and firstName is not None:
		employee_list = EmployeeDetail.objects.filter(first_name__icontains = firstName)

	if lastName != '' and lastName is not None:
		employee_list = EmployeeDetail.objects.filter(last_name__icontains = lastName)
	
	paginator = Paginator(employee_list, 50)
	page = request.GET.get('page')
	employee_list = paginator.get_page(page)
	user           = request.user
	employee       = Employee.objects.get(auth_tbl=user)
	rolename       = employee.role.name.lower()

	context = {
		'emps':employee_list,
		'role':rolename
	}
	return render(request,'letter/employee_list.html',context)


def generatePDF(request,pk):
	employee = EmployeeDetail.objects.get(id=pk)
	salary_annually = employee.ctc
	words_salary = convertToWords(salary_annually)

	basic_annual = get_basic_annually(salary_annually)
	house_rent_al_annual = get_house_rent_allowance_annually(salary_annually)
	city_al_annual = get_city_allowance_annually(salary_annually)
	conveyance_al_annual = get_conveyance_allowance_annually(salary_annually)
	children_education_al_annual = get_children_education_allowance_annually(salary_annually)
	medical_al_annual = get_medical_allowance_annually(salary_annually)
	special_al_annual = get_special_allowance_annually(salary_annually)

	gross_salary_annually = get_gross_annually(basic_annual,
		house_rent_al_annual,city_al_annual,
		conveyance_al_annual,children_education_al_annual,
		medical_al_annual,special_al_annual)

	pf_annually = get_pf_annually(salary_annually)
	
	#more tds conditions need to be added.
	tds_annually = get_tds_annually(salary_annually)

	net_payable_salary_annually = get_net_salary_annually(gross_salary_annually,pf_annually,tds_annually)

	context = {
		'name':employee,
		'date':datetime.datetime.now().date,
		'designation':employee.designation,
		'joining_date':employee.joining_date,
		'ctc':salary_annually,

		'basic_annual':basic_annual,
		'house_rent_allowance_annual':house_rent_al_annual,
		'city_allowance_annual':city_al_annual,
		'conveyance_allowance_annual':conveyance_al_annual,
		'children_education_allowance_annual':children_education_al_annual,
		'medical_allowance_annual':medical_al_annual,
		'special_allowance_annual':special_al_annual,

		'basic_monthly':math.floor(basic_annual/12),
		'house_rent_allowance_monthly':math.floor(house_rent_al_annual/12),
		'city_allowance_monthly':math.floor(city_al_annual/12),
		'conveyance_allowance_monthly':math.floor(conveyance_al_annual/12),
		'children_education_allowance_monthly':math.floor(children_education_al_annual/12),
		'medical_allowance_monthly':math.floor(medical_al_annual/12),
		'special_allowance_monthly':math.floor(special_al_annual/12),

		'gross_salary_annually':gross_salary_annually,
		'gross_salary_monthly':math.floor(gross_salary_annually/12),
		
		'words_salary':words_salary,
		'pf_annually':pf_annually,
		'pf_monthly':math.floor(pf_annually/12),
		'tds_annually':tds_annually,
		'tds_monthly':math.floor(tds_annually/12),
		'net_payable_salary_annually':net_payable_salary_annually,
		'net_payable_salary_monthly':math.floor(net_payable_salary_annually/12),

	}
	return render(request,'letter/offer_letter.html',context)

letter/templates/letter/add_employee.html
{% extends 'user_invoice/base.html' %}
{% load static %}
{% block title %}Add Employee{% endblock title %}
<link rel="stylesheet" href="{% static 'css/letter.css' %}">

{% block content %}
<div class="container">
    <h2 class='text-center mt-2 text-danger'><u style="color: teal;">Offer Letter</u></h2>
   
    <form action="" method="POST" autocomplete="off">
        {% csrf_token %}
        <p class="text-center" style="color: red;">( <span class="text-danger">*</span> fields are required fields )</p>
        <p style="color: teal;"> <b>
            Select User :</b>
            <select id="get_user">
                <option value="">User</option>
                {% for user in users %}
                    <option value="{{user.id}}">{{user.firstname}} {{user.lastname}}</option>
                {% endfor %}
            </select> 
        </p>
        <div class="form-group">
            <label for="exampleInputEmail1" style="color: teal;">First Name:</label><span class="text-danger">*</span>
            <input type="text" class="form-control" required value="{{joinee.first_name}}" name="first_name" id="first_name" aria-describedby="emailHelp" placeholder="Enter First Name">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" style="color: teal;">Last Name:</label><span class="text-danger">*</span>
            <input type="text" class="form-control" required value="{{joinee.last_name}}" name="last_name" id="last_name" aria-describedby="emailHelp" placeholder="Enter Last Name">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" style="color: teal;">Designation:</label><span class="text-danger">*</span>
            <input type="text" class="form-control" required value="{{joinee.designation}}" name="designation" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Designation">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" style="color: teal;">CTC:</label><span class="text-danger">*</span>
            <input type="number" class="form-control" required value="{{joinee.ctc}}" name="ctc" maxlength="10" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Annual Salary(Gross Salary)">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" style="color: teal;">Email:</label>
            <input type="email" class="form-control" name="email" value="{{joinee.email}}" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" style="color: teal;">Phone:</label>
            <input type="text" class="form-control" value="{{joinee.phone}}" name="phone" maxlength="10" id="phone" aria-describedby="emailHelp" placeholder="Enter Phone Number">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1" style="color: teal;">Joining Date:</label><span class="text-danger">*</span>
            <input type="date" class="form-control"  required value="{{joinee.joining_date|date:'Y-m-d'}}" name="joining_date" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Joining Date">
        </div>
        
        <button type="submit" style="margin-bottom: 80px" class="btn btn-outline-success">Submit</button>
    </form>
</div>
<style>
	body{
		background-color: #EFCFB0;
	}
	html{
		background-color: #EFCFB0;
	}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    $("#get_user").change(function(){
        var user_id = $(this).val()
        if (user_id != ""){ 
            $.ajax({
              url  : '{% url "letter:get_user_data" %}',
              data : {
                    user_id  : user_id,
                  },
              type : 'GET',
              dataType: 'json',
              success: function (data) {
                $("#first_name").val(data.firstname)
                $("#last_name").val(data.lastname)
                $("#phone").val(data.phone)
                $("#email").val(data.email)
                
              }
            });
        }
        
    })
</script>
{% endblock content %}

letter/templates/letter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock title %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="{% static 'css/letter.css' %}">
	<style>
		@page {
			margin: 0;
		}
		
		.head{
			text-align: right;
		}
		
		div.para{
			word-spacing: 5px;
			text-align:justify;
		}
		
		div.address{
			margin-top:100px;
		
			line-height: 10px;
		}
		
		.heading{
			margin-left: -10rem;
			margin-top:6rem;
		}
		
		td{
			text-align: right;
		}
	</style>
</head>

<body>
	<div class="container">
		{% block content %}
		
		
		{% endblock content %}
	</div>

</body>

	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://kit.fontawesome.com/aa2decd2e9.js"></script>

</html>

letter/templates/letter/employee_list.html
{% extends 'user_invoice/base.html' %}
{% load static %}

{% block title %}Employee List{% endblock title %}

<link rel="stylesheet" href="{% static 'css/letter.css' %}">

{% block content %}

	<div class='row'>
		<div class="col-12">
			<h2 class="mt-5"><a href="{% url 'letter:joinee_list' %}" class='text-success'><b style="color: teal;text-decoration: underline;"> Employee List: </b></a></h2>
			<a href="{% url 'letter:add_joinee' %}" class='text-info'><button class="btn btn-primary" style="margin-bottom: 15px;float: right;">Add New</button></a>
		</div>
		<div class="col-6">
	
		
		</div>
	</div>
		<div class="row">
				<form class="form-inline" method="POST" action="">
					{% csrf_token %}
					<label class="sr-only" for="inlineFormInputName2">First Name</label>
					<input type="text" name="first_name" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Enter First Name">
				  
					<label class="sr-only" for="inlineFormInputGroupUsername2">Last Name</label>
					<div class="input-group mb-2 mr-sm-2">
						<input type="text" name="last_name" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Enter Last Name">
					</div>
					<button type="submit" class="btn btn-primary mb-2">Search</button>
				  </form>
		</div>
		<div class="list">
			<table class="table">
				<thead>
					<tr>
						<th scope="col" style="color: teal;">#</th>
						<th scope="col" style="color: teal;">Employee Name</th>
						<th scope="col" style="color: teal;">Offer Letter</th>
					</tr>
				</thead>
				<tbody>
					{% for e in emps %}
					<tr>
						<th scope="row">{{ forloop.counter }}</th>
						
						<td class="text-left"><a href="{% url 'letter:edit_joinee' e.id %}" class='text-info'><button class="btn btn-primary" style="margin-bottom: 15px;float: right;"> Edit</button></a>{{ e }}</td>
						<td class="text-left"><a href="{% url 'letter:pdf-generate' e.id %}"><button class="btn btn-primary">Generate</button></a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="mt-5" style="align-items: center;justify-content: center; display: flex;">
			<ul class="pagination">
				{% if emps.has_previous %}
				<li class="page-item">
					<a class="page-link" href="?page={{ emps.previous_page_number }}">&laquo; Prev</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="?page={{ i }}">&laquo; Prev</a>
				</li>
				{% endif %}
				{% for i in emps.paginator.page_range %}
				{% if emps.number == i %}
				<li class="page-item">
					<a class="page-link active" id=myid  href="?page={{ i }}">{{i}}</a>
				</li>
				{% else %}
				<li class="page-item">
					<a class="nav-link" id=myid  href="?page={{ i }}">{{i}}</a>
				</li>
				{% endif %}
				{% endfor %}
				{% if emps.has_next %}
				<li class="page-item">
					<a class="page-link" href="?page={{ emps.next_page_number }}">Next &raquo;</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="?page={{ i }}">Next &raquo;</a>
				</li>
				{% endif %}
			</ul>
		</div>
		<style>
			html{
				background-color: #EFCFB0;
			}
			body{
				background-color: #EFCFB0;
			}
		</style>

{% endblock content %}